name: Continuous Integration
on: [push, pull_request]
env:
  PROJECT_NAME: s3dol
jobs:
  validation:
    name: Validation
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: S3 Localstack
        run: |
          export S3_TEST_ENDPOINT_RW=http://localhost:4566
          export S3_TEST_BUCKET_RW=test-bucket
          export S3_TEST_ACCESS_RW=access
          export S3_TEST_SECRET_RW=secret
          docker run -d -e SERVICES=s3 -p 4566:4566 --name localstack localstack/localstack

      - uses: i2mint/isee/actions/validation@master
        with:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          python-version: ${{ matrix.python-version }}
          use-setup-cfg: true

  publish:
    name: Publish
    if: "!contains(github.event.head_commit.message, '[skip ci]') && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')"
    needs: validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: i2mint/isee/actions/publish@master
        with:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          python-version: ${{ matrix.python-version }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  github-pages:
    name: Publish GitHub Pages
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: i2mint/epythet/actions/publish-github-pages@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
